//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Emp_id { get; set; }
        [Required(ErrorMessage = "Please enter Name.")]
        public string Emp_Name { get; set; }
        [Required(ErrorMessage = "Please enter Gender.")]
        public string Emp_gender { get; set; }
        [Required(ErrorMessage = "Please enter  Age.")]
        public string Emp_age { get; set; }
        [Required(ErrorMessage = "Please enter designation.")]
        public string Emp_designation { get; set; }
        [Required(ErrorMessage = "Please enter  Salary.")]
        public int Emp_Salary { get; set; }
    }
}
